name: Samsung Beta Forums Monitor

on:
  schedule:
    - cron: '30 2 * * *'   # 8:00 AM IST
    - cron: '30 6 * * *'   # 12:00 PM IST
    - cron: '30 10 * * *'  # 4:00 PM IST
    - cron: '30 12 * * *'  # 6:00 PM IST
    - cron: '30 16 * * *'  # 10:00 PM IST

jobs:
  check-forums:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run forum checker
      run: python ./check_forums.py
